{% set name = "mercurial" %}
{% set version = "4.3.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "47a63c78698bc735667984bbc5b76619ff29a38d742f20cdf9f44cce59752374" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools  # [win]
  build:
    - {{ compiler('c') }}
  run:
    - python
    - pygments

test:
  commands:
    - hg --version
  imports:
    - hgdemandimport
    - hgext
    - hgext.convert
    - hgext.fsmonitor
    - hgext.fsmonitor.pywatchman
    - hgext.fsmonitor.pywatchman.bser
    - hgext.highlight
    - hgext.largefiles
    - hgext.zeroconf
    - hgext3rd
    - mercurial
    - mercurial.cext
    - mercurial.cffi
    - mercurial.hgweb
    - mercurial.httpclient
    - mercurial.pure

about:
  home: http://mercurial-scm.org
  license: GPL2
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a free, distributed source control management tool. It
    efficiently handles projects of any size and offers an easy and intuitive
    interface.
  doc_url: https://www.mercurial-scm.org/guide
  dev_url: https://www.mercurial-scm.org/repo/hg

extra:
  recipe-maintainers:
    - ngoldbaum
    - nehaljwani
