{% set version = "5.5.2" %}
{% set sha256 = "84930ad47a25d1f5db47acf48662bd199e45b7c331d8af6f4a8c46449ad8f372" %}

package:
  name: mercurial
  version: {{ version }}

source:
  fn: mercurial-{{ version }}.tar.gz
  url: https://mercurial-scm.org/release/mercurial-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools  # [win]
  run:
    - python
    - pygments
    - setuptools  # [win]

test:
  commands:
    - hg --version
  imports:
    - hgdemandimport
    - hgext
    - hgext.convert
    - hgext.fsmonitor
    - hgext.fsmonitor.pywatchman
    - hgext.fsmonitor.pywatchman.bser
    - hgext.highlight
    - hgext.infinitepush
    - hgext.largefiles
    - hgext.lfs
    - hgext.narrow
    - hgext.zeroconf
    - hgext3rd
    - mercurial
    - mercurial.cext
    - mercurial.cffi
    - mercurial.hgweb
    - mercurial.pure
    - mercurial.utils

about:
  home: http://mercurial-scm.org
  license: GPL2
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a free, distributed source control management tool. It
    efficiently handles projects of any size and offers an easy and intuitive
    interface.
  doc_url: https://www.mercurial-scm.org/guide
  dev_url: https://www.mercurial-scm.org/repo/hg

extra:
  recipe-maintainers:
    - ngoldbaum
    - nehaljwani
