{% set version = "3.9.2" %}

package:
  name: mercurial
  version: {{ version }}

source:
  fn: mercurial-{{ version }}.tar.gz
  url: https://mercurial-scm.org/release/mercurial-{{ version }}.tar.gz
  sha256: 69046a427c05e83097bf0145a1e37975ae0b6ba4430456e2beca3d2fd96583cf

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - hg --version

about:
  home: http://mercurial-scm.org
  license: GPL2
  license_file: COPYING
  summary: Source control management tool

extra:
  recipe-maintainers:
    - ngoldbaum
