{% set version = "4.5.3" %}
{% set sha256 = "9c4cb257ef1e59e9aba693cc285a6136f7bb4e8300f598ff50ff8b6fc77808fc" %}

package:
  name: mercurial
  version: {{ version }}

source:
  fn: mercurial-{{ version }}.tar.gz
  url: https://mercurial-scm.org/release/mercurial-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools  # [win]
  build:
    - {{ compiler('c') }}
  run:
    - python
    - pygments
    - setuptools  # [win]

test:
  commands:
    - hg --version
  imports:
    - hgdemandimport
    - hgext
    - hgext.convert
    - hgext.fsmonitor
    - hgext.fsmonitor.pywatchman
    - hgext.fsmonitor.pywatchman.bser
    - hgext.highlight
    - hgext.largefiles
    - hgext.zeroconf
    - hgext3rd
    - mercurial
    - mercurial.cext
    - mercurial.cffi
    - mercurial.hgweb
    - mercurial.httpclient
    - mercurial.pure

about:
  home: http://mercurial-scm.org
  license: GPL2
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a free, distributed source control management tool. It
    efficiently handles projects of any size and offers an easy and intuitive
    interface.
  doc_url: https://www.mercurial-scm.org/guide
  dev_url: https://www.mercurial-scm.org/repo/hg

extra:
  recipe-maintainers:
    - ngoldbaum
    - nehaljwani
