{% set version = "4.4" %}
{% set sha256 = "234af4a67565c85923b0a1910c704ab44bcf12f69b85532687208776563d87de" %}

package:
  name: mercurial
  version: {{ version }}

source:
  fn: mercurial-{{ version }}.tar.gz
  url: https://mercurial-scm.org/release/mercurial-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py3k]
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools  # [win]
  build:
    - {{ compiler('c') }}
  run:
    - python
    - setuptools  # [win]

test:
  commands:
    - hg --version

about:
  home: http://mercurial-scm.org
  license: GPL2
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a free, distributed source control management tool. It
    efficiently handles projects of any size and offers an easy and intuitive
    interface.
  doc_url: https://www.mercurial-scm.org/guide
  dev_url: https://www.mercurial-scm.org/repo/hg

extra:
  recipe-maintainers:
    - ngoldbaum
