travis:
  secure:
    BINSTAR_TOKEN: Dw5X5/Y+rgoZmEWx4tJtI/TgjnS6UMUhv8J9+HjkxcRFBd7kXS2sKIPweVHwBWShgLZpNEwsS2FkMzti8r//vTsTisHPMOWlZmz7y/2w7oXPlkpfZAedtcpk12Hk7YPj4kwiV+TC1DuUumLYScBG82Dx4CLI5IP0C7T7Q0vV3VGQcmQXlLM34sGNbbb/v4uPxwlVK5fIlIdpOqQnK3fwZiVeEkzxQJeut9iGdoaOOBrzx0B/OPxkpdWQJAOA38Qx5kIEByaOSSwvwFsQ+EHgEj4r4p5jupRGn0aIBmyEwG2bWFxuhHw/oUMZw07qsJd9fKiHBsJQz1tvHhfSTQNm1P1oKW80IgDDpGWKryeKN2sLsx4RWlglrvEd06QNg6+f8UqAIhWd59ORgsox3GeAnuxAyMDQRvIvrJPEfJeTk6Meqr0YL0hO3OoEux904/4rgoO2Y12FyHhejV/LxLFEQnSyNfGeEzsW5eU3u/a1YILOJCgzLRr3mk/JdUtWpbRJI4uQQECd7z3Nzo69yMtAiZvCy6KTCXnYd60lVqsu1OvbcrWxBdtLNthU7YFAETVZNH8WbGw7Hp5ncicqNgFXmTWQOxfM9DqhYq7AA15CaLwlHVCHB1hRXBtR9b2TN2A7qpuegBo97vEnIE7+4oS+oTnGJr5BHgGMxCDLVR5jAw4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
